-- mira - 36 Product catalog from Excel
-- Ejecutar despues de 35_internal_staff.sql.
-- Carga el catalogo base desde LISTA DE PRODUCTOS.xlsx usando nombre comercial e ingrediente activo.

alter table public.task_materials
add column if not exists composition text;

create index if not exists products_company_name_lookup_idx
on public.products(company_id, lower(trim(name)));

create index if not exists task_materials_product_id_idx
on public.task_materials(product_id)
where product_id is not null;

with raw_products(name, composition) as (
  values
    ('16-10-15 TH', nullif('Nitrógeno (N) 16.00% P/V, Fósforo (P2O5) 10.00% P/V, Potasio (K20) 15.00% P/V, Ac. Húmicos 05.00% P/V, Ac. Fúlvicos 05.00% p/v, Magnesio (Mg) 100 ppm, Hierro (Fe) 500 ppm, Zinc (Zn) 500 ppm, Manganeso (Mn) 100 ppm, Boro (B) 80 ppm, Cobre (Cu) 50 ppm, Molibdeno (Mo) 2 ppm, AATC 3000 ppm, AGB 30 ppm, CTQ 500 ppm.', '')),
    ('ACIDIX PH', nullif('Alcohol etioxilado C8-C10. (Equivalente a 215.72 g de i.a./L). Acido citrico (Equivalente a 215.72 g de i.a./L). 20%', '')),
    ('ACIDO FOSFORICO 85 %', nullif('P2O5 51-54 %', '')),
    ('ACIDO SULFURICO', nullif('Fierro (Fe) 50 ppp max, arsenico (As) 0.5 ppm max, nitratos (NO3-) 10 ppm max, metales pesados (Pb) 0.5 ppm max', '')),
    ('AGRI BAT', nullif('Nitrogeno (N) 1.25%, Fosforo (P2O5) 2.80%, Potasio (K2O) 2.90%, Materia Organica 20.77%, Acidos húmicos 41%, Ácidos fúlvicos 5.02% Calcio (CaO) 3.10%, Magnesio (MgO) 2.74%, Hierro (Fe) 0.042%, Zinc (Zn) 0.02 %, Manganeso (Mn) 0.024%, Boro (B) 0.016%, Cobre (Cu) 0.23%, Azufre (S) 0.30%', '')),
    ('ALMIRANTE CA', nullif('Óxido de Calcio y óxido de Magnesio.', '')),
    ('AMBIOS XPR', nullif('Polisulfuros, extracto vegetal de gobernadora (Equivalente a 690.60 g. de i.a./L + 138.12 g. de i.a./L) 10%, ingredientes inertes 40%', '')),
    ('AMINO BIO 85', nullif('Aminoácidos totales 80%, Nitrógeno total 16%', '')),
    ('AMINOSHOT', nullif('Aminoácidos totales 80.00% p/p (Glicina, Acido glutámico, Prolina y Arginina)', '')),
    ('APOLO', nullif('Bacillus subtilis 1.85X10(8) UFC/g, Trichoderma sp 5.11x10(8) esp/g, Streptomyces lydicus 1.06X10(6) esp/g, Silicio Orgánico 2.019% P/P, Materia orgánica(extractos vegetales) 60.73% P/P', '')),
    ('ARMITEN', nullif('Trichoderma viride / harzianum 9 x 10 UFC/L (Equivalente a 100 g de i.a./ L a 20°C) 10 %', '')),
    ('AZUFRE GRANULADO', nullif('Azufre (S) 99.5%', '')),
    ('B3', nullif('Beauveria bassiana no menos de 50x106 UFC Ml; Paecilomyces fumosoroseus no menos de 50x106 UFC /Ml; Metarhizium anisopliae no menos de 50 x 106 UFC/Ml', '')),
    ('BACILLUS 4', nullif('Bacillus subtilis 20%, Bacillus amyloliquefaciens 20%, Bacillus pumilus 20 %, Bacillus megaterium 20% Torulopsis inconspicua 20 %.', '')),
    ('BACTIRVEN', nullif('Trioxonitrato de cobre (equivalente a 341.60 g. de i.a./L) 28%, Diluyentes naturales 72%', '')),
    ('BACTRIX', nullif('Extracto vegetal de gobernadora 12%, cobre carboxilado (equivalente a 128.88 g. de i.a./ L + 165.40 g. de i.a/L) 15.4%, acondicionadores y diluyentes naturales 72.6%', '')),
    ('BEAUVERIA', nullif('Beauveria bassiana (3.678 g de i.a./L a 20 °C, Equivalente a 1 x10 11 UFC/L).', '')),
    ('BETAGLI MAX', nullif('Glicin Betaina 98 % (p/p)', '')),
    ('BIO AK', nullif('Dioctil sulfosuccinato de sodio 70%', '')),
    ('BIO ALGA', nullif('Extracto de algas marinas (Ascophyllum nodosum) 75 %, Ácidos húmicos y fúlvicos 15%, materiales inertes 10%.', '')),
    ('BIO EVES', nullif('Glomus intraradices, Glomus mosseae, Glomus aggregatum, Glomus etunicatum. Azospirillum lipoferum, Rhizophagus irregularis, Trinchoderma spp', '')),
    ('BIO ROOT', nullif('Extractos de Algas marinas 22.0%, ácidos fúlvicos 30.0%, fósforo asimilable (PO) 09.0%, aminoácidos 05.0%, L cisteína 00.3%, auxinas 5,000 ppm, citoquininas 40 ppm', '')),
    ('BIOFULMIX', nullif('Base de minerales y compuestos organicos, ácidos húmicos y fúlvicos.', '')),
    ('BIOGROW', nullif('Azospirillum brasilense 1.0 x 108 UFC/Ml, Bacillus subtilis 1.0 x 107 UFC/mL, Micorriza 1.0 x 104 esporas/mL .', '')),
    ('BIOHUMIC', nullif('Nitrógeno total (N) 0.06 mgL-1, Fósforo total (P) 49.21 mgL-1, Potasio total (K) 849.79 mgL-1, Boro (B) 0.57 mgL -1, Manganeso (Mn) 0.54 mgL-1, Zinc (Zn) 0.58 mgL-1, Cobre (Cu) 0.40 mgL -1, Hierro (Fe) 6.5 mgL-1, Aluminio (Al) 13.55 mgL-1, Calcio(Ca) 74.71 mgL-1, Magnesio (Mg) 79.65 mgL-1, Sodio (Na) 304.38 mgL-1', '')),
    ('BIOMATTER 8-24-1', nullif('Lixiviado de lombriz, adicionado con fuetes de nitrogeno, fosforoy potasio', '')),
    ('BMo PLUS', nullif('Nitrógeno (N) 8.40% , Boro (B) 6.25 %, Molibdeno (Mo) 0.76%, aminoácidos libres 13.3%, materia orgánica s.ms. 26.70%', '')),
    ('BORAX', nullif('Tetraborato Disódico Pentahidratado', '')),
    ('BRIXFULL', nullif('Potasio (K2O) 25 % p/v, Boro (B) 1.74% p/v, Ácidos húmicos 8.29% p/v, Polisacáridos 14.30% p/v', '')),
    ('CAPITAN', nullif('Nitrógeno total (N) 31.00% p/p, Nitrógeno Nítrico 15.10% p/p , Nitrógeno Amoniacal, Fósforo (P2O5) 3.00% p/p , Potasio (K2O) 3.00% p/p.', '')),
    ('CHARGER OIDIUM', nullif('Polisulfuros, extractos vegetales de gobernadora (Polifenoles)(equivalente a 148.57 g. de i.a./L+190.67 g. de i.a./L), acondicionadores y diluyentes naturales 72.6%', '')),
    ('CITROCOVER', nullif('Extracto de semillas de citricos en una mezcla compuesta 3-(3hidroxipropoxy) - 1, 2 propanodiol, a una concentracion del 8% en peso del I.A. equivalente a 80 g/L (80000 ppm/L)', '')),
    ('CLEAN ROOT', nullif('Paecilomyces lilacinus 25%, Bacillus methylotrophicus 20%, Glomus spp 30%, Paecilomyces fumosoroseus 25%', '')),
    ('CLORURO DE POTASIO', nullif('Potasio (K2O) 62.00 % P/P', '')),
    ('COBREX', nullif('Sulfato de cobre (CuSO4. 5H2O) con un contenido de cobre metalico de 4.96% en peso 21.50% p/v, Ingredientes Inertes, Diluyentes y coadyuvantes 78.50 % p/v', '')),
    ('COBREX 4 G', nullif('Cuaternario de amonio equivalente a 494 g de I.A. 20 °C 50 %, Sulfato de cobre pentahidratado 20%. Equivalente a 296.43 g de I.A. a 20 °C', '')),
    ('COMODORO', nullif('Extrato de Tagetes (Tagetes erecta L) 20%, equivalente a 180 g/L de I.A. Aceite escencial de Lemongrass (Cymbopogon citratus) 08.00%, Equivalente a 72 g/L de I.A.', '')),
    ('CRECIMAX TH', nullif('Extractos de algas marinas (Ascophyllum nodosum) 50 % p/v, ácidos fúlvicos 40 % p/v, aminoácidos 05.0% p/v, giberelinas 3000 ppm, citocilinas 3000 ppm, auxinas 750 ppm.', '')),
    ('DAP', nullif('Nitrógeno total (N) 18.00% P/P, Fósforo 46.00% p/p', '')),
    ('DIA-FIX', nullif('Diatomita o tierra diatomácea(Dióxido de silicio formado por algas fosilizadas)', '')),
    ('DIAFIX-PLUS', nullif('Tierras diatomeas + extractos vegetales', '')),
    ('DOLOMITA (MGC-100', nullif('MGC- DOLOMITA (Carbonato de sodio)', '')),
    ('EDAFOS', nullif('Nbelyax 8%, ácido carboxílicos 5%', '')),
    ('EXODUSMAX', nullif('Nbelyax', '')),
    ('FACTOR COLOIDAL EKO', nullif('Polímeros orgánicos, proteínas y polisacáridos 6.05 P/V, • Polímeros silícicos 7.77 P/V', '')),
    ('FERRO MANGANESO MAX', nullif('Óxido de hierro y manganeso', '')),
    ('FERRO ZINC MAX', nullif('Óxido de hierro y zinc', '')),
    ('FIERRO SUPREME', nullif('Hierro 4% p/p', '')),
    ('FOGONERO', nullif('Lecanicillium spp. Beauveria spp. Metarhizium spp. (Equivalentes a 51.2 gi.a./L con 1x10 6 UFC/ ml viables) 80%, Bacillus thuringiensis (equivalente a 51.2 g i.a./L con 1x10 9 UFC/ml viables) 0.5% Quitosano (equivalente a 5.12 g i.a./L) Inertes (diuyentes) 79.5%', '')),
    ('FOSFI K PLUS', nullif('Fósforo (P2O5) 44.1%, Potasio (K2O) 29.4%', '')),
    ('FOSFI MG PLUS', nullif('Fósforo (P2O5) 61.1% P/V, Magnesio (MgO) 14.2% P/V', '')),
    ('FOSFI Q', nullif('Fósforo (P2O5) 58.70% p/v, Cobre (Cu) 5.25 % p/v', '')),
    ('FOSFI ZN PLUS', nullif('Fósforo (P2O5) 58.70%, Cobre (Cu) 5.25%', '')),
    ('FULVIPOWER 95', nullif('Ácidos fúlvicos ≥95%', '')),
    ('FUNGIZUM', nullif('', '')),
    ('GEYSER', nullif('', '')),
    ('GOTA VERDE', nullif('Mezcla de extractos de vegetales (Ruta graveolens, Argemone mexicana, Azaridachta y Ricinus communis) 90 %', '')),
    ('GRAMMIT TS', nullif('Glomus intraradices 108 esp/g, Bacterias fijadoras de nitrogeno 1.281 x 105 UFC/g, Bacillus sp 2.55x107 UFC/g, Hongo solubilizadores de Fósforo 1.079x106 esp/g, Zinc coloidal 4510.200 ppm, Auxinas 504.400 ppm, Extractos vegetales 60.56% p/p', '')),
    ('K-45 PLUS', nullif('Potasio (K2O) 45.0% p/v', '')),
    ('KASTELO', nullif('Paecilomyces lilacinus 7 x 10(7) esp/g, Quitosano 4.508% P/P, Extractos vegetales 60.6% P/P, Silicio orgánico 1.004% P/P', '')),
    ('KINNA', nullif('Extracto de canela (Cinnamomum Zeylanicum) equivalente a 234 g de I.A. a 23 °C', '')),
    ('KONTRA S-3', nullif('Potasio (K2O) 8.50% p/p , Calcio (CaO) 3.40% p/p, Magnesio (MgO) 1.35% p/p, Boro (B) 0.23% p/p', '')),
    ('LARREA T', nullif('Mezcla de extracto de gobernadora (Larrea tridenta) y (Eucalyptus globulus).', '')),
    ('LEONARDITA (AHF-100)', nullif('Leonardita', '')),
    ('LIVING COMPLETE', nullif('Microelementos Quelatados con EDTA, (Hierro (Fe) EDTA 6.00% p/p , Cobre (Cu) EDTA 0.25% p/p, Manganeso (Mn) EDTA 2.4% p/p, Zinc (Zn) EDTA 1.3% P/P, Boro (B) 1.1 % P/P, Molibdeno (Mo) 0.25% P/P, Cobalto (Co) 0.03% P/P', '')),
    ('LIVING X6 FE', nullif('Hierro (Fe) EDDHSA 6.00 % P/P', '')),
    ('LIVING X7 EDDHA', nullif('Zinc (Zn) EDDHA 7.00% p/p', '')),
    ('LIVING X8 PLATINUM EDDHA', nullif('Hierro (Fe) EDDHA 4.5% p/p, Manganeso (Mn) EDDHA 1.0% p/p, zinc (Zn) EDDHA 0.5 % P/P', '')),
    ('MAGNATUS FOSETYL', nullif('Fosfonato de aluminio 80%, Ácidos orgánicos y disolventes 20 %.', '')),
    ('MAGNESITA (MG-100)', nullif('Carbonato 4.09%, Nitrógeno (N) 3.99%, Silicio 28.42%, Magnesio 27.36%, Calcio 8.73%, Hierro (FeO) 3.87%, Aluminio 1.18%, Níquel (Ni) 0.14%, Potasio 0.105%, Manganeso 0.072%, Fósforo 0.05, PXC 16.17%', '')),
    ('MAJESTY', nullif('Extractos vegetales 26.46%, diluyentes naturales 73.54%', '')),
    ('MAP ISAOSA 25 KG', nullif('Nitrógeno 12%, Fósforo 61%', '')),
    ('MAXI START', nullif('Magnesio 1.70% p/p, Hierro (Fe) 0.50% p/p, Manganeso (Mn) 0.25% p/p, Cobre (Cu) 0.25% p/p, Boro(B) 0.25 % p/p, Molibdeno (Mo) 0.004% p/p, Zinc (Zn) 0.14% p/p, Azufre (S) 1.40% p/p', '')),
    ('MG SUPREME', nullif('Magnesio (MgO) 10.5% P/P, Boro (B) 0.5 % P/P', '')),
    ('MKP ISAOSA 25 KG', nullif('Fósforo (P2O5) 52.23% p/p, Potasio (K2O) 34.08% p/p', '')),
    ('NATURAL SOAP', nullif('Sales potásicas de ácidos grasos. (Equivalente a 506.50 g 1.a/L a 20 °C).', '')),
    ('NAUTILUS', nullif('Nitrógeno total (N) 0.75%, Fósforo (P2O5) 0.5%, , Potasio (K2O) 1.2%, Calcio (CA) 0.09%, Magnesio (Mg) 0.07%, Hierro (Fe) 0.002%, Zinc (Zn) 0.001%, Manganeso (MN) 0.0001%, Boro (B) 0.001%, Cobre (Cu) 0.0009%, Azufre (S) 0.19, Carbohidratos 4.9%, Aminoácidos totales 0.41%.', '')),
    ('NCA ISAOSA 25 KG', nullif('Nitrógeno Total (N) 15.14% p/p, Calcio (CaO) 24.88% p/p', '')),
    ('NEEM CE 80', nullif('Mezcla de extractos de neem (Azadirachta indica) y Tomillo (Thymus vulgaris) 80', '')),
    ('NEMAT-X', nullif('Extractos de plantas y minerales, Dióxido de silicio + silicato de aluminio.', '')),
    ('NITRATO DE MAGNESIO 25 KG', nullif('Magnesio (MgO) 14.60% P/P, Azufre (S) 13.50 p/p', '')),
    ('NITROGENO SUPREME', nullif('Nitrógeno (N) 24% P/P', '')),
    ('NKS ISAOSA 25 KG', nullif('Nitrógeno Total (N) 12.66% P/P, Potasio (K2O) 46.30% p/p, Azufre (SO3) 3 .05% p/p', '')),
    ('OKUOS OCEAN CRECIMIENTO 26-06-17', nullif('', '')),
    ('OKUOS OCEAN PRODUCCION 12-05-35', nullif('Nitrógeno total (N) 12.37% P/P, Nitrógeno nítrico 9.44 % p/p, Nitrógeno amoniacal 2.94% p/p, Fósforo (P2O5) 5.20% p/p,Potasio (k2O) 35.00% p/p, Azufre (SO4)5.24% P/P, Hiero (Fe) 520 ppm, Zinc (Zn) 500 ppm, Manganeso (Mn) 390 ppm, Cobre (Cu) 300 ppm, Boro (B) 420 ppm, Molibdeno (Mo) 42 ppm.', '')),
    ('ORGAMAG', nullif('Magnesio (Mg), Calcio (Ca), Hierro (Fe)', '')),
    ('ORTHO P OPTIMO', nullif('Fósforo 23% p/p, Potasio 3% p/p, Zinc (Zn) 1% p/p, Calcio (Cao) 3.50% p/p', '')),
    ('PECTA CA', nullif('Calcio (CaO) 11.20% P/P, Boro (B) 0.5% P/P', '')),
    ('PODER SIN STRESS', nullif('Aldosas 19%, Cetosas 13.5%, Oligosacáridos 1.06%, Antioxidantes fúlvicos 17%, Aminoácidos 4.8%, Diluyentes orgánicos 44.64%.', '')),
    ('POTASIO SUPREME', nullif('Potasio (K2O) 24.00% p/p', '')),
    ('POWER MIX', nullif('Alcohol tridecílico polioxietilénico 30%, ácido fosfórico 12 %, diluyentes y acondicionadores 58%.', '')),
    ('PROGUANO', nullif('Extracto de Guano de murcielago 40.00% + Extracto de sustancias orgánicas 25.00 % + Diluyentes orgánicos 35.00', '')),
    ('PUREX BIOSANITIZER', nullif('Peróxido de Hidrógeno 12.43%, ácido Peracético 1.23%', '')),
    ('Q VIRUS', nullif('lodo libre', '')),
    ('RE. BUILDER', nullif('Thiobacillus denitrificans 15%, Azospirillum brasilense 15%, Bacillus megaterium 15%, Azotobacter sp. 15%, Glomus iraníicum tenuihypharum 10%, Frateuria aurantía 15%, Pseudomonas fluorescens 15%.', '')),
    ('RED FIRE', nullif('Mezcla de extractos vegetales. Ajo (Allium sativum), chile picante (Capsicum frutensces), Canela (Cinnamomum zeylanicum y tomillo (Thymus vulgaris) (Equivalente a 76.00 g de i.a. /L) 80 %', '')),
    ('REPPEL', nullif('Extracto de ajo(Allium sativum). Equivalente a 588 g de I.A a 20 °C, Extracto de neem (Azaridachta indica) Equivalente a 55 g de I.A. A 20 °C 0.05%', '')),
    ('ROCA FOSFORICA (RP-100', nullif('Fosforita', '')),
    ('ROJA POTASICA (BK-100)', nullif('Arcilla potasica', '')),
    ('ROMEL', nullif('Brevibacillus spp.', '')),
    ('ROOT BOOST', nullif('Pseudomonas fluorescens 10%, Glomus iranicum tenulhypharum 10%, Bacillus megaterium 10%, Azospirillum brasilense 10%, Nitrógeno (N), 1%, Fósforo (P2O5) 6%, Potasio (K2O) 1%, Citocininas 0.06%, Auxinas 0.03%, Giberelinas 0.02%', '')),
    ('SA-PROPEL RTU', nullif('Sulfato de potasio (K2SO4) en Cadenas de Carbono (C) con oxígeno (O) doble enlace 1.69% (p/v)', '')),
    ('SILEX', nullif('Ácido orto silícico 33.577%, Humectantes y disolventes orgánicos 66.423%', '')),
    ('SOP ISAOSA 25 KG', nullif('Potasio (K2O) 51.00% p/p, Azufre (S) 18.00% p/p', '')),
    ('SPINOSINAS 4X', nullif('Saccharopolyspora spinosa tipo A: 50%, Saccharopolyspora spinosa tipo D:50%', '')),
    ('STOP SOL', nullif('Minerales y extractos orgánicos', '')),
    ('STÄRKE ZINC', nullif('• Zinc (Zn) 50%', '')),
    ('SUELO. RX', nullif('Ácidos húmicos 24%, Ácidos fúlvicos 8%, Aminoácidos 9%, Ácidos fúlvicos 1%, Aminoácidos 8%.', '')),
    ('SULFATO DE COBRE', nullif('Cobre (Cu) 25.1 % min, Fierro (Fe) 0.04 % max, Plomo (Pb) 5 ppm max, zinc (Zn) 65 ppm max, niquel (Ni) 25 ppm max.', '')),
    ('SULFATO DE ZINC', nullif('Zinc (Zn) 35.5% (Derivado del sulfato de zinc monohídrico)', '')),
    ('SULMAG PEÑOLES 50 KG', nullif('Magnesio MgO % Min 16.20, Magnesio (Mg) % Min. 9.80, Azufre % Min 12.90, Cloruro % Max. 0.15', '')),
    ('SUPRA ANTISAL', nullif('Nitrogeno (N) 3%, Calcio 3%, Ácidos Fúlvicos 3%, Ácido polihidroxicarboxílicos 3%, Potasio coloidal (K2O) 3%, Azufre coloidal 4%', '')),
    ('SUPRA B', nullif('BORO (B) 8%, Diluyentes y acondicionadores 92%', '')),
    ('SUPRA Ca', nullif('Calcio (Ca) 14%, Diluyentes y acondicionadores 86%', '')),
    ('SUPRA CARB PLUS', nullif('Nitrógeno Total (N) 12%, Fósforo (PO) 9%, Potasio (KO) 7%, Hierro (Fe) 0.050%, Zinc (Zn) 0.08%, Manganeso (Mn) 0.03%, Cobre (Cu) 0.04%, Boro (B) 0.03%, Calcio (Ca) 0.15%, Magnesio (Mg) 0.20%, Azufre (S) 0.40%, Molibdeno (Mo) 0.005%, Ácidos Fúlvicos 2%, Aminoácidos Libres 0.05%, Vitaminas Libres 0.08%.', '')),
    ('SUPRA ENGORDE', nullif('Potasio coloidal (K2O) 15%, Azufre coloidal (S) 2.5%, Fulvato de potasio 2%, Fitohormonas (Citocininas) 200 PPM,', '')),
    ('SUPRA Fe', nullif('Hierro (Fe) 6 %, Diluyentes y acondicionadores 94%', '')),
    ('SUPRA GRAMM SC', nullif('Nitrógeno (N) 10.10, Nitrógeno Amoniacal 5%, Nitrógeno Nítrico 4.7%, Nitrógeno Ureico 0.4%, Fosforo (P2O5) 20%, Potasio (K2O 10%), Calcio (CaO) 0.487, Magnesio (MgO) 0.65%, Azufre (S) 0.344%, Boro (B) 0.108%, Cobre (Cu) 0.293%, Hierro (Fe) 0.856%, Manganeso (Mn) EDTA 0.303%, Molibdeno (Mo) 0.42%, Zinc (Zn) 0.412 %, Aminoácidos libres 1%.', '')),
    ('SUPRA HARD', nullif('Calcio (Ca) 9%, Boro (B) 0.25%, Diluyentes y acondicionadores 80.75%', '')),
    ('SUPRA HORMONAL', nullif('Citocininas 3128 ppm, Giberelinas 48 ppm, Auxinas 42 ppm, vitaminas 2608 ppm, ácido carboxilicos 0.147%, Disacáridos totales 1.985%', '')),
    ('SUPRA K', nullif('Potasio coloidal (K2o) 5.50 %, azufre coloidal 18%', '')),
    ('SUPRA Mg', nullif('Magnesio (Mg) 6%, Diluyentes y acondicionadores 94%', '')),
    ('SUPRA MIX', nullif('Hierro (Fe) 6%, Zinc (Zn) 1.6%, Manganeso (Mn) 1.3%, Magnesio (Mg) 0.75 %, Boro (B) 0.40%, Cobre (Cu) 0.15%, Molibdeno (Mo) 0.030%, Diluyentes y acondicionadores Naturales 89.5%', '')),
    ('SUPRA ROOT', nullif('Nitrógeno (N), Fósforo (P2O5), Diluyentes y acondicionadores, Ácido Naftalenacético (ANA), Ácido Indolbutírico (AIB)', '')),
    ('SUPRA START', nullif('NITROGENO (N) 5.4%, FOSFORO COLOIDAL (PO) 30%, ACIDOS HÚMICOS 6.10%,', '')),
    ('SUPRA START BIO', nullif('Bacterias fijadoras de nitrógeno 1 x 10(5) UFC/g, Hongos solubilizadores de de fósforo 1x10(6) esp/g, Bacillus subtilis 1x10(7) UFC/g, polímeros orgánicos de priteínas y polisacáridos 20.22%, fosforo coloidal 3.00 %, Auxinas 9000 ppm, Zinc coloidal 14000 ppm, Boro coloidal 4160 ppm, Calcio coloidal 62400 ppm, Cobre coloidal 0.102 ppm, Hierro coloidal 31200 ppm, Manganeso coloida 1.3 ppm, Molibdeno coloidal 0.102 ppm.', '')),
    ('SUPRA Zn', nullif('Zinc (Zn) 6%, Diluyentes y acondicionadores 94%', '')),
    ('TAGETES', nullif('Mezcla de extracto de Tagetes (Tagetes erecta) y extracto de pino ( Pinus sylvestris) (Equivalente a 855.00 g de I.A./L a 20 °C )', '')),
    ('TOTAL 4G', nullif('Cuaternario de amonio de ultima generacion 12.30 %, Vehiculo c.b.p. 1000 ml.', '')),
    ('TRICHO 3 EXPANSIVE', nullif('Trichoderma harzianum 40%, Trichoderma reesei, Trichoderma viride 30%', '')),
    ('TUNDRA', nullif('Extracto vegetal de gobernadora (Equivalente a 389.61 g. de i.a./L) 39%, Diluyentes naturales 61%', '')),
    ('TURIN-VK', nullif('Bacillus thuringiensis var. Kurstaki (Equivalente a 2.2 g de i.a./L a 20 °C. 0.22%P/V', '')),
    ('VEGETAL OIL', nullif('Aceite de soya (Glycine Max) 95%', '')),
    ('VIRO STOP', nullif('Nitrógeno (N) 1.13 % P/P, Fósforo 2.02 % p/p, Potasio 4% p/p, Boro (B) 0.850 % p/p, materia orgánica 25 % p/p, aminoácidos libres 1.56% p/p, ácido salicilico 4.30 % p/p.', '')),
    ('VITAPHOS', nullif('Fósforo + minerales', '')),
    ('VOLTAN', nullif('Bacterias Heterotróficas Aerobias 1x10⁸ UFC/g, Bacterias Fijadoras de Nitrógeno 1x10⁶ UFC/g, Hongos Solubilizadores de Fósforo 2x10⁶ esp/g, Trichoderma harzianum 1x10⁵ esp/g, Pisolithus tinctorius 5x10⁶ esp/g, Extractos Vegetales 40 % P/P.', '')),
    ('X P-1', nullif('Poliéter polisiloxano modificado (Equivalente a 820.56 g de i.a ./L a 20° C). 80%', '')),
    ('ZEOFERT (S-100)', nullif('Nitrógeno (N) 3%, Fósforo (P) 9%, Potasio (K) 2%, Calcio (Ca) 15%, Magnesio (Mg) 2 %, Azufre (S) 1%, Silice (Si) 19%, Hierro (Fe) 2%, Manganeso (Mn) 0.05%, Cobre (Cu) 6 ppm, Boro (B) 16 ppm, Zinc (Zn) 281 ppm, Molibdeno (Mo) 3 ppm, Colbato (Co) 13 ppm, ácidos húmicos y fúlvicos', '')),
    ('ZEOFOL', nullif('Nitrógeno (N) 3.74%, Fósforo (P) 9.38%, Potasio (K) 2.06%, Calcio (Ca) 16.05%, Magnesio (Mg) 3.35 %, Azufre (S) 2.97%, Silice (Si) 38.93%, Hierro (Fe) 2.68%, Manganeso (Mn) 0.26%, Aluminio 1.05 % , Sodio 0.21%, Cobre (Cu) 4.05 ppm, Boro (B) 4.72, Zinc (Zn) 0.25, Molibdeno (Mo) 1.7 ppm, Colbato (Co) 13 ppm.', '')),
    ('ZEOLITA (ZN -100)', nullif('100 % Zeolita Clinoptilolita natural', '')),
    ('ZERENO', nullif('Ácidos fúlvicos 40 % p/p, Polipéptidos 10.00% p/p, Extracto de algas Ascophyllum nodosum (origen Canadá) 10.00% p/p, Nitrógeno total (N) 4.00% p/p, Fósforo (P2O5) 7.00% p/p, Potasio (K2O) 14.00% p/p, Calcio EDTA (Ca) 0.30% p/p, Magnesio EDTA (Mg) 0.10% p/p, Zinc EDTA (Zn) 0.20% p/p , Hierro EDTA (Fe) 1.00% p/p , Manganeso EDTA (Mn) 0.05% p/p, Cobre EDTA (Cu) 0.05% p/p, Boro (B) 0.08% p/p , Molibdeno (Mo) 0.05% p/p.', '')),
    ('ÁCIDO NITRICO 55%', nullif('Nitrogeno (N) 12.2 %', ''))
),
source_products as (
  select distinct on (lower(trim(name)))
    trim(name) as name,
    nullif(trim(composition), '') as composition
  from raw_products
  where nullif(trim(name), '') is not null
  order by lower(trim(name)), (nullif(trim(composition), '') is not null) desc
)
update public.products product
set composition = source.composition,
    updated_at = now()
from source_products source
where product.company_id is not null
  and lower(trim(product.name)) = lower(trim(source.name))
  and source.composition is not null
  and nullif(trim(coalesce(product.composition, '')), '') is null;

with raw_products(name, composition) as (
  values
    ('16-10-15 TH', nullif('Nitrógeno (N) 16.00% P/V, Fósforo (P2O5) 10.00% P/V, Potasio (K20) 15.00% P/V, Ac. Húmicos 05.00% P/V, Ac. Fúlvicos 05.00% p/v, Magnesio (Mg) 100 ppm, Hierro (Fe) 500 ppm, Zinc (Zn) 500 ppm, Manganeso (Mn) 100 ppm, Boro (B) 80 ppm, Cobre (Cu) 50 ppm, Molibdeno (Mo) 2 ppm, AATC 3000 ppm, AGB 30 ppm, CTQ 500 ppm.', '')),
    ('ACIDIX PH', nullif('Alcohol etioxilado C8-C10. (Equivalente a 215.72 g de i.a./L). Acido citrico (Equivalente a 215.72 g de i.a./L). 20%', '')),
    ('ACIDO FOSFORICO 85 %', nullif('P2O5 51-54 %', '')),
    ('ACIDO SULFURICO', nullif('Fierro (Fe) 50 ppp max, arsenico (As) 0.5 ppm max, nitratos (NO3-) 10 ppm max, metales pesados (Pb) 0.5 ppm max', '')),
    ('AGRI BAT', nullif('Nitrogeno (N) 1.25%, Fosforo (P2O5) 2.80%, Potasio (K2O) 2.90%, Materia Organica 20.77%, Acidos húmicos 41%, Ácidos fúlvicos 5.02% Calcio (CaO) 3.10%, Magnesio (MgO) 2.74%, Hierro (Fe) 0.042%, Zinc (Zn) 0.02 %, Manganeso (Mn) 0.024%, Boro (B) 0.016%, Cobre (Cu) 0.23%, Azufre (S) 0.30%', '')),
    ('ALMIRANTE CA', nullif('Óxido de Calcio y óxido de Magnesio.', '')),
    ('AMBIOS XPR', nullif('Polisulfuros, extracto vegetal de gobernadora (Equivalente a 690.60 g. de i.a./L + 138.12 g. de i.a./L) 10%, ingredientes inertes 40%', '')),
    ('AMINO BIO 85', nullif('Aminoácidos totales 80%, Nitrógeno total 16%', '')),
    ('AMINOSHOT', nullif('Aminoácidos totales 80.00% p/p (Glicina, Acido glutámico, Prolina y Arginina)', '')),
    ('APOLO', nullif('Bacillus subtilis 1.85X10(8) UFC/g, Trichoderma sp 5.11x10(8) esp/g, Streptomyces lydicus 1.06X10(6) esp/g, Silicio Orgánico 2.019% P/P, Materia orgánica(extractos vegetales) 60.73% P/P', '')),
    ('ARMITEN', nullif('Trichoderma viride / harzianum 9 x 10 UFC/L (Equivalente a 100 g de i.a./ L a 20°C) 10 %', '')),
    ('AZUFRE GRANULADO', nullif('Azufre (S) 99.5%', '')),
    ('B3', nullif('Beauveria bassiana no menos de 50x106 UFC Ml; Paecilomyces fumosoroseus no menos de 50x106 UFC /Ml; Metarhizium anisopliae no menos de 50 x 106 UFC/Ml', '')),
    ('BACILLUS 4', nullif('Bacillus subtilis 20%, Bacillus amyloliquefaciens 20%, Bacillus pumilus 20 %, Bacillus megaterium 20% Torulopsis inconspicua 20 %.', '')),
    ('BACTIRVEN', nullif('Trioxonitrato de cobre (equivalente a 341.60 g. de i.a./L) 28%, Diluyentes naturales 72%', '')),
    ('BACTRIX', nullif('Extracto vegetal de gobernadora 12%, cobre carboxilado (equivalente a 128.88 g. de i.a./ L + 165.40 g. de i.a/L) 15.4%, acondicionadores y diluyentes naturales 72.6%', '')),
    ('BEAUVERIA', nullif('Beauveria bassiana (3.678 g de i.a./L a 20 °C, Equivalente a 1 x10 11 UFC/L).', '')),
    ('BETAGLI MAX', nullif('Glicin Betaina 98 % (p/p)', '')),
    ('BIO AK', nullif('Dioctil sulfosuccinato de sodio 70%', '')),
    ('BIO ALGA', nullif('Extracto de algas marinas (Ascophyllum nodosum) 75 %, Ácidos húmicos y fúlvicos 15%, materiales inertes 10%.', '')),
    ('BIO EVES', nullif('Glomus intraradices, Glomus mosseae, Glomus aggregatum, Glomus etunicatum. Azospirillum lipoferum, Rhizophagus irregularis, Trinchoderma spp', '')),
    ('BIO ROOT', nullif('Extractos de Algas marinas 22.0%, ácidos fúlvicos 30.0%, fósforo asimilable (PO) 09.0%, aminoácidos 05.0%, L cisteína 00.3%, auxinas 5,000 ppm, citoquininas 40 ppm', '')),
    ('BIOFULMIX', nullif('Base de minerales y compuestos organicos, ácidos húmicos y fúlvicos.', '')),
    ('BIOGROW', nullif('Azospirillum brasilense 1.0 x 108 UFC/Ml, Bacillus subtilis 1.0 x 107 UFC/mL, Micorriza 1.0 x 104 esporas/mL .', '')),
    ('BIOHUMIC', nullif('Nitrógeno total (N) 0.06 mgL-1, Fósforo total (P) 49.21 mgL-1, Potasio total (K) 849.79 mgL-1, Boro (B) 0.57 mgL -1, Manganeso (Mn) 0.54 mgL-1, Zinc (Zn) 0.58 mgL-1, Cobre (Cu) 0.40 mgL -1, Hierro (Fe) 6.5 mgL-1, Aluminio (Al) 13.55 mgL-1, Calcio(Ca) 74.71 mgL-1, Magnesio (Mg) 79.65 mgL-1, Sodio (Na) 304.38 mgL-1', '')),
    ('BIOMATTER 8-24-1', nullif('Lixiviado de lombriz, adicionado con fuetes de nitrogeno, fosforoy potasio', '')),
    ('BMo PLUS', nullif('Nitrógeno (N) 8.40% , Boro (B) 6.25 %, Molibdeno (Mo) 0.76%, aminoácidos libres 13.3%, materia orgánica s.ms. 26.70%', '')),
    ('BORAX', nullif('Tetraborato Disódico Pentahidratado', '')),
    ('BRIXFULL', nullif('Potasio (K2O) 25 % p/v, Boro (B) 1.74% p/v, Ácidos húmicos 8.29% p/v, Polisacáridos 14.30% p/v', '')),
    ('CAPITAN', nullif('Nitrógeno total (N) 31.00% p/p, Nitrógeno Nítrico 15.10% p/p , Nitrógeno Amoniacal, Fósforo (P2O5) 3.00% p/p , Potasio (K2O) 3.00% p/p.', '')),
    ('CHARGER OIDIUM', nullif('Polisulfuros, extractos vegetales de gobernadora (Polifenoles)(equivalente a 148.57 g. de i.a./L+190.67 g. de i.a./L), acondicionadores y diluyentes naturales 72.6%', '')),
    ('CITROCOVER', nullif('Extracto de semillas de citricos en una mezcla compuesta 3-(3hidroxipropoxy) - 1, 2 propanodiol, a una concentracion del 8% en peso del I.A. equivalente a 80 g/L (80000 ppm/L)', '')),
    ('CLEAN ROOT', nullif('Paecilomyces lilacinus 25%, Bacillus methylotrophicus 20%, Glomus spp 30%, Paecilomyces fumosoroseus 25%', '')),
    ('CLORURO DE POTASIO', nullif('Potasio (K2O) 62.00 % P/P', '')),
    ('COBREX', nullif('Sulfato de cobre (CuSO4. 5H2O) con un contenido de cobre metalico de 4.96% en peso 21.50% p/v, Ingredientes Inertes, Diluyentes y coadyuvantes 78.50 % p/v', '')),
    ('COBREX 4 G', nullif('Cuaternario de amonio equivalente a 494 g de I.A. 20 °C 50 %, Sulfato de cobre pentahidratado 20%. Equivalente a 296.43 g de I.A. a 20 °C', '')),
    ('COMODORO', nullif('Extrato de Tagetes (Tagetes erecta L) 20%, equivalente a 180 g/L de I.A. Aceite escencial de Lemongrass (Cymbopogon citratus) 08.00%, Equivalente a 72 g/L de I.A.', '')),
    ('CRECIMAX TH', nullif('Extractos de algas marinas (Ascophyllum nodosum) 50 % p/v, ácidos fúlvicos 40 % p/v, aminoácidos 05.0% p/v, giberelinas 3000 ppm, citocilinas 3000 ppm, auxinas 750 ppm.', '')),
    ('DAP', nullif('Nitrógeno total (N) 18.00% P/P, Fósforo 46.00% p/p', '')),
    ('DIA-FIX', nullif('Diatomita o tierra diatomácea(Dióxido de silicio formado por algas fosilizadas)', '')),
    ('DIAFIX-PLUS', nullif('Tierras diatomeas + extractos vegetales', '')),
    ('DOLOMITA (MGC-100', nullif('MGC- DOLOMITA (Carbonato de sodio)', '')),
    ('EDAFOS', nullif('Nbelyax 8%, ácido carboxílicos 5%', '')),
    ('EXODUSMAX', nullif('Nbelyax', '')),
    ('FACTOR COLOIDAL EKO', nullif('Polímeros orgánicos, proteínas y polisacáridos 6.05 P/V, • Polímeros silícicos 7.77 P/V', '')),
    ('FERRO MANGANESO MAX', nullif('Óxido de hierro y manganeso', '')),
    ('FERRO ZINC MAX', nullif('Óxido de hierro y zinc', '')),
    ('FIERRO SUPREME', nullif('Hierro 4% p/p', '')),
    ('FOGONERO', nullif('Lecanicillium spp. Beauveria spp. Metarhizium spp. (Equivalentes a 51.2 gi.a./L con 1x10 6 UFC/ ml viables) 80%, Bacillus thuringiensis (equivalente a 51.2 g i.a./L con 1x10 9 UFC/ml viables) 0.5% Quitosano (equivalente a 5.12 g i.a./L) Inertes (diuyentes) 79.5%', '')),
    ('FOSFI K PLUS', nullif('Fósforo (P2O5) 44.1%, Potasio (K2O) 29.4%', '')),
    ('FOSFI MG PLUS', nullif('Fósforo (P2O5) 61.1% P/V, Magnesio (MgO) 14.2% P/V', '')),
    ('FOSFI Q', nullif('Fósforo (P2O5) 58.70% p/v, Cobre (Cu) 5.25 % p/v', '')),
    ('FOSFI ZN PLUS', nullif('Fósforo (P2O5) 58.70%, Cobre (Cu) 5.25%', '')),
    ('FULVIPOWER 95', nullif('Ácidos fúlvicos ≥95%', '')),
    ('FUNGIZUM', nullif('', '')),
    ('GEYSER', nullif('', '')),
    ('GOTA VERDE', nullif('Mezcla de extractos de vegetales (Ruta graveolens, Argemone mexicana, Azaridachta y Ricinus communis) 90 %', '')),
    ('GRAMMIT TS', nullif('Glomus intraradices 108 esp/g, Bacterias fijadoras de nitrogeno 1.281 x 105 UFC/g, Bacillus sp 2.55x107 UFC/g, Hongo solubilizadores de Fósforo 1.079x106 esp/g, Zinc coloidal 4510.200 ppm, Auxinas 504.400 ppm, Extractos vegetales 60.56% p/p', '')),
    ('K-45 PLUS', nullif('Potasio (K2O) 45.0% p/v', '')),
    ('KASTELO', nullif('Paecilomyces lilacinus 7 x 10(7) esp/g, Quitosano 4.508% P/P, Extractos vegetales 60.6% P/P, Silicio orgánico 1.004% P/P', '')),
    ('KINNA', nullif('Extracto de canela (Cinnamomum Zeylanicum) equivalente a 234 g de I.A. a 23 °C', '')),
    ('KONTRA S-3', nullif('Potasio (K2O) 8.50% p/p , Calcio (CaO) 3.40% p/p, Magnesio (MgO) 1.35% p/p, Boro (B) 0.23% p/p', '')),
    ('LARREA T', nullif('Mezcla de extracto de gobernadora (Larrea tridenta) y (Eucalyptus globulus).', '')),
    ('LEONARDITA (AHF-100)', nullif('Leonardita', '')),
    ('LIVING COMPLETE', nullif('Microelementos Quelatados con EDTA, (Hierro (Fe) EDTA 6.00% p/p , Cobre (Cu) EDTA 0.25% p/p, Manganeso (Mn) EDTA 2.4% p/p, Zinc (Zn) EDTA 1.3% P/P, Boro (B) 1.1 % P/P, Molibdeno (Mo) 0.25% P/P, Cobalto (Co) 0.03% P/P', '')),
    ('LIVING X6 FE', nullif('Hierro (Fe) EDDHSA 6.00 % P/P', '')),
    ('LIVING X7 EDDHA', nullif('Zinc (Zn) EDDHA 7.00% p/p', '')),
    ('LIVING X8 PLATINUM EDDHA', nullif('Hierro (Fe) EDDHA 4.5% p/p, Manganeso (Mn) EDDHA 1.0% p/p, zinc (Zn) EDDHA 0.5 % P/P', '')),
    ('MAGNATUS FOSETYL', nullif('Fosfonato de aluminio 80%, Ácidos orgánicos y disolventes 20 %.', '')),
    ('MAGNESITA (MG-100)', nullif('Carbonato 4.09%, Nitrógeno (N) 3.99%, Silicio 28.42%, Magnesio 27.36%, Calcio 8.73%, Hierro (FeO) 3.87%, Aluminio 1.18%, Níquel (Ni) 0.14%, Potasio 0.105%, Manganeso 0.072%, Fósforo 0.05, PXC 16.17%', '')),
    ('MAJESTY', nullif('Extractos vegetales 26.46%, diluyentes naturales 73.54%', '')),
    ('MAP ISAOSA 25 KG', nullif('Nitrógeno 12%, Fósforo 61%', '')),
    ('MAXI START', nullif('Magnesio 1.70% p/p, Hierro (Fe) 0.50% p/p, Manganeso (Mn) 0.25% p/p, Cobre (Cu) 0.25% p/p, Boro(B) 0.25 % p/p, Molibdeno (Mo) 0.004% p/p, Zinc (Zn) 0.14% p/p, Azufre (S) 1.40% p/p', '')),
    ('MG SUPREME', nullif('Magnesio (MgO) 10.5% P/P, Boro (B) 0.5 % P/P', '')),
    ('MKP ISAOSA 25 KG', nullif('Fósforo (P2O5) 52.23% p/p, Potasio (K2O) 34.08% p/p', '')),
    ('NATURAL SOAP', nullif('Sales potásicas de ácidos grasos. (Equivalente a 506.50 g 1.a/L a 20 °C).', '')),
    ('NAUTILUS', nullif('Nitrógeno total (N) 0.75%, Fósforo (P2O5) 0.5%, , Potasio (K2O) 1.2%, Calcio (CA) 0.09%, Magnesio (Mg) 0.07%, Hierro (Fe) 0.002%, Zinc (Zn) 0.001%, Manganeso (MN) 0.0001%, Boro (B) 0.001%, Cobre (Cu) 0.0009%, Azufre (S) 0.19, Carbohidratos 4.9%, Aminoácidos totales 0.41%.', '')),
    ('NCA ISAOSA 25 KG', nullif('Nitrógeno Total (N) 15.14% p/p, Calcio (CaO) 24.88% p/p', '')),
    ('NEEM CE 80', nullif('Mezcla de extractos de neem (Azadirachta indica) y Tomillo (Thymus vulgaris) 80', '')),
    ('NEMAT-X', nullif('Extractos de plantas y minerales, Dióxido de silicio + silicato de aluminio.', '')),
    ('NITRATO DE MAGNESIO 25 KG', nullif('Magnesio (MgO) 14.60% P/P, Azufre (S) 13.50 p/p', '')),
    ('NITROGENO SUPREME', nullif('Nitrógeno (N) 24% P/P', '')),
    ('NKS ISAOSA 25 KG', nullif('Nitrógeno Total (N) 12.66% P/P, Potasio (K2O) 46.30% p/p, Azufre (SO3) 3 .05% p/p', '')),
    ('OKUOS OCEAN CRECIMIENTO 26-06-17', nullif('', '')),
    ('OKUOS OCEAN PRODUCCION 12-05-35', nullif('Nitrógeno total (N) 12.37% P/P, Nitrógeno nítrico 9.44 % p/p, Nitrógeno amoniacal 2.94% p/p, Fósforo (P2O5) 5.20% p/p,Potasio (k2O) 35.00% p/p, Azufre (SO4)5.24% P/P, Hiero (Fe) 520 ppm, Zinc (Zn) 500 ppm, Manganeso (Mn) 390 ppm, Cobre (Cu) 300 ppm, Boro (B) 420 ppm, Molibdeno (Mo) 42 ppm.', '')),
    ('ORGAMAG', nullif('Magnesio (Mg), Calcio (Ca), Hierro (Fe)', '')),
    ('ORTHO P OPTIMO', nullif('Fósforo 23% p/p, Potasio 3% p/p, Zinc (Zn) 1% p/p, Calcio (Cao) 3.50% p/p', '')),
    ('PECTA CA', nullif('Calcio (CaO) 11.20% P/P, Boro (B) 0.5% P/P', '')),
    ('PODER SIN STRESS', nullif('Aldosas 19%, Cetosas 13.5%, Oligosacáridos 1.06%, Antioxidantes fúlvicos 17%, Aminoácidos 4.8%, Diluyentes orgánicos 44.64%.', '')),
    ('POTASIO SUPREME', nullif('Potasio (K2O) 24.00% p/p', '')),
    ('POWER MIX', nullif('Alcohol tridecílico polioxietilénico 30%, ácido fosfórico 12 %, diluyentes y acondicionadores 58%.', '')),
    ('PROGUANO', nullif('Extracto de Guano de murcielago 40.00% + Extracto de sustancias orgánicas 25.00 % + Diluyentes orgánicos 35.00', '')),
    ('PUREX BIOSANITIZER', nullif('Peróxido de Hidrógeno 12.43%, ácido Peracético 1.23%', '')),
    ('Q VIRUS', nullif('lodo libre', '')),
    ('RE. BUILDER', nullif('Thiobacillus denitrificans 15%, Azospirillum brasilense 15%, Bacillus megaterium 15%, Azotobacter sp. 15%, Glomus iraníicum tenuihypharum 10%, Frateuria aurantía 15%, Pseudomonas fluorescens 15%.', '')),
    ('RED FIRE', nullif('Mezcla de extractos vegetales. Ajo (Allium sativum), chile picante (Capsicum frutensces), Canela (Cinnamomum zeylanicum y tomillo (Thymus vulgaris) (Equivalente a 76.00 g de i.a. /L) 80 %', '')),
    ('REPPEL', nullif('Extracto de ajo(Allium sativum). Equivalente a 588 g de I.A a 20 °C, Extracto de neem (Azaridachta indica) Equivalente a 55 g de I.A. A 20 °C 0.05%', '')),
    ('ROCA FOSFORICA (RP-100', nullif('Fosforita', '')),
    ('ROJA POTASICA (BK-100)', nullif('Arcilla potasica', '')),
    ('ROMEL', nullif('Brevibacillus spp.', '')),
    ('ROOT BOOST', nullif('Pseudomonas fluorescens 10%, Glomus iranicum tenulhypharum 10%, Bacillus megaterium 10%, Azospirillum brasilense 10%, Nitrógeno (N), 1%, Fósforo (P2O5) 6%, Potasio (K2O) 1%, Citocininas 0.06%, Auxinas 0.03%, Giberelinas 0.02%', '')),
    ('SA-PROPEL RTU', nullif('Sulfato de potasio (K2SO4) en Cadenas de Carbono (C) con oxígeno (O) doble enlace 1.69% (p/v)', '')),
    ('SILEX', nullif('Ácido orto silícico 33.577%, Humectantes y disolventes orgánicos 66.423%', '')),
    ('SOP ISAOSA 25 KG', nullif('Potasio (K2O) 51.00% p/p, Azufre (S) 18.00% p/p', '')),
    ('SPINOSINAS 4X', nullif('Saccharopolyspora spinosa tipo A: 50%, Saccharopolyspora spinosa tipo D:50%', '')),
    ('STOP SOL', nullif('Minerales y extractos orgánicos', '')),
    ('STÄRKE ZINC', nullif('• Zinc (Zn) 50%', '')),
    ('SUELO. RX', nullif('Ácidos húmicos 24%, Ácidos fúlvicos 8%, Aminoácidos 9%, Ácidos fúlvicos 1%, Aminoácidos 8%.', '')),
    ('SULFATO DE COBRE', nullif('Cobre (Cu) 25.1 % min, Fierro (Fe) 0.04 % max, Plomo (Pb) 5 ppm max, zinc (Zn) 65 ppm max, niquel (Ni) 25 ppm max.', '')),
    ('SULFATO DE ZINC', nullif('Zinc (Zn) 35.5% (Derivado del sulfato de zinc monohídrico)', '')),
    ('SULMAG PEÑOLES 50 KG', nullif('Magnesio MgO % Min 16.20, Magnesio (Mg) % Min. 9.80, Azufre % Min 12.90, Cloruro % Max. 0.15', '')),
    ('SUPRA ANTISAL', nullif('Nitrogeno (N) 3%, Calcio 3%, Ácidos Fúlvicos 3%, Ácido polihidroxicarboxílicos 3%, Potasio coloidal (K2O) 3%, Azufre coloidal 4%', '')),
    ('SUPRA B', nullif('BORO (B) 8%, Diluyentes y acondicionadores 92%', '')),
    ('SUPRA Ca', nullif('Calcio (Ca) 14%, Diluyentes y acondicionadores 86%', '')),
    ('SUPRA CARB PLUS', nullif('Nitrógeno Total (N) 12%, Fósforo (PO) 9%, Potasio (KO) 7%, Hierro (Fe) 0.050%, Zinc (Zn) 0.08%, Manganeso (Mn) 0.03%, Cobre (Cu) 0.04%, Boro (B) 0.03%, Calcio (Ca) 0.15%, Magnesio (Mg) 0.20%, Azufre (S) 0.40%, Molibdeno (Mo) 0.005%, Ácidos Fúlvicos 2%, Aminoácidos Libres 0.05%, Vitaminas Libres 0.08%.', '')),
    ('SUPRA ENGORDE', nullif('Potasio coloidal (K2O) 15%, Azufre coloidal (S) 2.5%, Fulvato de potasio 2%, Fitohormonas (Citocininas) 200 PPM,', '')),
    ('SUPRA Fe', nullif('Hierro (Fe) 6 %, Diluyentes y acondicionadores 94%', '')),
    ('SUPRA GRAMM SC', nullif('Nitrógeno (N) 10.10, Nitrógeno Amoniacal 5%, Nitrógeno Nítrico 4.7%, Nitrógeno Ureico 0.4%, Fosforo (P2O5) 20%, Potasio (K2O 10%), Calcio (CaO) 0.487, Magnesio (MgO) 0.65%, Azufre (S) 0.344%, Boro (B) 0.108%, Cobre (Cu) 0.293%, Hierro (Fe) 0.856%, Manganeso (Mn) EDTA 0.303%, Molibdeno (Mo) 0.42%, Zinc (Zn) 0.412 %, Aminoácidos libres 1%.', '')),
    ('SUPRA HARD', nullif('Calcio (Ca) 9%, Boro (B) 0.25%, Diluyentes y acondicionadores 80.75%', '')),
    ('SUPRA HORMONAL', nullif('Citocininas 3128 ppm, Giberelinas 48 ppm, Auxinas 42 ppm, vitaminas 2608 ppm, ácido carboxilicos 0.147%, Disacáridos totales 1.985%', '')),
    ('SUPRA K', nullif('Potasio coloidal (K2o) 5.50 %, azufre coloidal 18%', '')),
    ('SUPRA Mg', nullif('Magnesio (Mg) 6%, Diluyentes y acondicionadores 94%', '')),
    ('SUPRA MIX', nullif('Hierro (Fe) 6%, Zinc (Zn) 1.6%, Manganeso (Mn) 1.3%, Magnesio (Mg) 0.75 %, Boro (B) 0.40%, Cobre (Cu) 0.15%, Molibdeno (Mo) 0.030%, Diluyentes y acondicionadores Naturales 89.5%', '')),
    ('SUPRA ROOT', nullif('Nitrógeno (N), Fósforo (P2O5), Diluyentes y acondicionadores, Ácido Naftalenacético (ANA), Ácido Indolbutírico (AIB)', '')),
    ('SUPRA START', nullif('NITROGENO (N) 5.4%, FOSFORO COLOIDAL (PO) 30%, ACIDOS HÚMICOS 6.10%,', '')),
    ('SUPRA START BIO', nullif('Bacterias fijadoras de nitrógeno 1 x 10(5) UFC/g, Hongos solubilizadores de de fósforo 1x10(6) esp/g, Bacillus subtilis 1x10(7) UFC/g, polímeros orgánicos de priteínas y polisacáridos 20.22%, fosforo coloidal 3.00 %, Auxinas 9000 ppm, Zinc coloidal 14000 ppm, Boro coloidal 4160 ppm, Calcio coloidal 62400 ppm, Cobre coloidal 0.102 ppm, Hierro coloidal 31200 ppm, Manganeso coloida 1.3 ppm, Molibdeno coloidal 0.102 ppm.', '')),
    ('SUPRA Zn', nullif('Zinc (Zn) 6%, Diluyentes y acondicionadores 94%', '')),
    ('TAGETES', nullif('Mezcla de extracto de Tagetes (Tagetes erecta) y extracto de pino ( Pinus sylvestris) (Equivalente a 855.00 g de I.A./L a 20 °C )', '')),
    ('TOTAL 4G', nullif('Cuaternario de amonio de ultima generacion 12.30 %, Vehiculo c.b.p. 1000 ml.', '')),
    ('TRICHO 3 EXPANSIVE', nullif('Trichoderma harzianum 40%, Trichoderma reesei, Trichoderma viride 30%', '')),
    ('TUNDRA', nullif('Extracto vegetal de gobernadora (Equivalente a 389.61 g. de i.a./L) 39%, Diluyentes naturales 61%', '')),
    ('TURIN-VK', nullif('Bacillus thuringiensis var. Kurstaki (Equivalente a 2.2 g de i.a./L a 20 °C. 0.22%P/V', '')),
    ('VEGETAL OIL', nullif('Aceite de soya (Glycine Max) 95%', '')),
    ('VIRO STOP', nullif('Nitrógeno (N) 1.13 % P/P, Fósforo 2.02 % p/p, Potasio 4% p/p, Boro (B) 0.850 % p/p, materia orgánica 25 % p/p, aminoácidos libres 1.56% p/p, ácido salicilico 4.30 % p/p.', '')),
    ('VITAPHOS', nullif('Fósforo + minerales', '')),
    ('VOLTAN', nullif('Bacterias Heterotróficas Aerobias 1x10⁸ UFC/g, Bacterias Fijadoras de Nitrógeno 1x10⁶ UFC/g, Hongos Solubilizadores de Fósforo 2x10⁶ esp/g, Trichoderma harzianum 1x10⁵ esp/g, Pisolithus tinctorius 5x10⁶ esp/g, Extractos Vegetales 40 % P/P.', '')),
    ('X P-1', nullif('Poliéter polisiloxano modificado (Equivalente a 820.56 g de i.a ./L a 20° C). 80%', '')),
    ('ZEOFERT (S-100)', nullif('Nitrógeno (N) 3%, Fósforo (P) 9%, Potasio (K) 2%, Calcio (Ca) 15%, Magnesio (Mg) 2 %, Azufre (S) 1%, Silice (Si) 19%, Hierro (Fe) 2%, Manganeso (Mn) 0.05%, Cobre (Cu) 6 ppm, Boro (B) 16 ppm, Zinc (Zn) 281 ppm, Molibdeno (Mo) 3 ppm, Colbato (Co) 13 ppm, ácidos húmicos y fúlvicos', '')),
    ('ZEOFOL', nullif('Nitrógeno (N) 3.74%, Fósforo (P) 9.38%, Potasio (K) 2.06%, Calcio (Ca) 16.05%, Magnesio (Mg) 3.35 %, Azufre (S) 2.97%, Silice (Si) 38.93%, Hierro (Fe) 2.68%, Manganeso (Mn) 0.26%, Aluminio 1.05 % , Sodio 0.21%, Cobre (Cu) 4.05 ppm, Boro (B) 4.72, Zinc (Zn) 0.25, Molibdeno (Mo) 1.7 ppm, Colbato (Co) 13 ppm.', '')),
    ('ZEOLITA (ZN -100)', nullif('100 % Zeolita Clinoptilolita natural', '')),
    ('ZERENO', nullif('Ácidos fúlvicos 40 % p/p, Polipéptidos 10.00% p/p, Extracto de algas Ascophyllum nodosum (origen Canadá) 10.00% p/p, Nitrógeno total (N) 4.00% p/p, Fósforo (P2O5) 7.00% p/p, Potasio (K2O) 14.00% p/p, Calcio EDTA (Ca) 0.30% p/p, Magnesio EDTA (Mg) 0.10% p/p, Zinc EDTA (Zn) 0.20% p/p , Hierro EDTA (Fe) 1.00% p/p , Manganeso EDTA (Mn) 0.05% p/p, Cobre EDTA (Cu) 0.05% p/p, Boro (B) 0.08% p/p , Molibdeno (Mo) 0.05% p/p.', '')),
    ('ÁCIDO NITRICO 55%', nullif('Nitrogeno (N) 12.2 %', ''))
),
source_products as (
  select distinct on (lower(trim(name)))
    trim(name) as name,
    nullif(trim(composition), '') as composition
  from raw_products
  where nullif(trim(name), '') is not null
  order by lower(trim(name)), (nullif(trim(composition), '') is not null) desc
)
insert into public.products (company_id, name, composition)
select company.id, source.name, source.composition
from public.companies company
cross join source_products source
where not exists (
  select 1
  from public.products product
  where product.company_id = company.id
    and lower(trim(product.name)) = lower(trim(source.name))
);
