export type NurseryVarietyPreset = {
  name: string;
  unit: "pieza" | "charola" | "charolas";
};

// Variedades y presentaciones recuperadas de los registros históricos del vivero.
export const NURSERY_VARIETY_PRESETS: NurseryVarietyPreset[] = [
  { name: "Agua Miel", unit: "pieza" },
  { name: "Agua Miel", unit: "charolas" },
  { name: "Agua Miel + Hércules doble tallo", unit: "pieza" },
  { name: "Agua Miel doble tallo", unit: "pieza" },
  { name: "Agua Miel doble tallo", unit: "charola" },
  { name: "Agua Miel doble tallo puntas", unit: "pieza" },
  { name: "Agua Miel franca", unit: "pieza" },
  { name: "Agua Miel puntas", unit: "pieza" },
  { name: "Agua Miel puntas 2 por cavidad", unit: "pieza" },
  { name: "Agua Miel un tallo", unit: "pieza" },
  { name: "Azovian", unit: "pieza" },
  { name: "Calabaza", unit: "pieza" },
  { name: "Calabaza de bola", unit: "pieza" },
  { name: "Calabaza larga", unit: "pieza" },
  { name: "Cedros doble tallo", unit: "pieza" },
  { name: "Chilacayote", unit: "pieza" },
  { name: "Chilacayote", unit: "charola" },
  { name: "CID + Hércules doble tallo", unit: "pieza" },
  { name: "CID doble tallo", unit: "pieza" },
  { name: "CID franca", unit: "pieza" },
  { name: "CID puntas 2 por cavidad", unit: "pieza" },
  { name: "Faraón + Tepex", unit: "charola" },
  { name: "Hércules-Lacio", unit: "charolas" },
  { name: "Inger franca", unit: "charolas" },
  { name: "King", unit: "charolas" },
  { name: "Lubino doble tallo", unit: "charola" },
  { name: "Macizo doble tallo", unit: "pieza" },
  { name: "Pepino", unit: "pieza" },
  { name: "Pepino Centauro", unit: "pieza" },
  { name: "Pepino Mondan", unit: "pieza" },
  { name: "Reserva", unit: "pieza" },
  { name: "Reserva", unit: "charolas" },
  { name: "Reserva doble tallo", unit: "pieza" },
  { name: "Riosal puntas", unit: "pieza" },
  { name: "Strogton", unit: "pieza" },
  { name: "Strogton doble tallo", unit: "pieza" },
  { name: "Strogton puntas", unit: "pieza" },
  { name: "Strogton puntas 2 por cavidad", unit: "pieza" },
  { name: "Stronto", unit: "charolas" },
  { name: "Stronton doble punta", unit: "pieza" },
  { name: "V27 doble tallo", unit: "pieza" },
  { name: "Villa", unit: "pieza" },
  { name: "Villa", unit: "charola" },
  { name: "Villa 2 por cavidad", unit: "pieza" },
  { name: "Villa 200 cavidades", unit: "pieza" },
  { name: "Villa doble punta", unit: "pieza" },
  { name: "Villa doble tallo", unit: "pieza" },
  { name: "Villa franca", unit: "pieza" },
  { name: "Ximador", unit: "pieza" },
  { name: "Ximador", unit: "charola" },
  { name: "Ximador doble tallo", unit: "charolas" },
  { name: "Ximador puntas", unit: "pieza" }
];
