-- Nursery commercial core.
-- Keeps nursery cash control separate from greenhouse harvest sales while reusing
-- Mira's company, membership, audit, and RLS foundations.

create table if not exists public.nurseries (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null default 'Vivero',
  code text not null default 'vivero',
  is_active boolean not null default true,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, company_id),
  unique (company_id, code),
  constraint nurseries_name_required check (nullif(trim(name), '') is not null),
  constraint nurseries_code_required check (nullif(trim(code), '') is not null)
);

create table if not exists public.nursery_customers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  display_name text not null,
  phone text,
  notes text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, company_id),
  constraint nursery_customers_name_required check (nullif(trim(display_name), '') is not null)
);

create index if not exists nursery_customers_company_name_idx
on public.nursery_customers(company_id, lower(display_name));

create table if not exists public.nursery_catalog_items (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  nursery_id uuid not null,
  item_kind text not null default 'seedling',
  name text not null,
  variety text,
  unit text not null default 'pieza',
  default_unit_price numeric(14,4),
  is_active boolean not null default true,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, company_id),
  foreign key (nursery_id, company_id)
    references public.nurseries(id, company_id) on delete cascade,
  constraint nursery_catalog_items_kind_valid check (
    item_kind in ('seedling', 'maquila', 'seed', 'freight', 'other')
  ),
  constraint nursery_catalog_items_name_required check (nullif(trim(name), '') is not null),
  constraint nursery_catalog_items_unit_required check (nullif(trim(unit), '') is not null),
  constraint nursery_catalog_items_price_non_negative check (
    default_unit_price is null or default_unit_price >= 0
  )
);

create unique index if not exists nursery_catalog_items_natural_key_idx
on public.nursery_catalog_items (
  nursery_id,
  lower(name),
  lower(coalesce(variety, '')),
  lower(unit)
);

create table if not exists public.nursery_sales (
  id uuid primary key default gen_random_uuid(),
  folio bigint generated by default as identity,
  company_id uuid not null references public.companies(id) on delete cascade,
  nursery_id uuid not null,
  customer_id uuid,
  sale_kind text not null default 'seedling',
  payment_terms text not null default 'cash',
  occurred_at date not null,
  due_date date,
  total_amount numeric(14,2) not null,
  notes text,
  source_reference text,
  cancelled_at timestamptz,
  cancellation_reason text,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, company_id),
  foreign key (nursery_id, company_id)
    references public.nurseries(id, company_id) on delete restrict,
  foreign key (customer_id, company_id)
    references public.nursery_customers(id, company_id) on delete restrict,
  constraint nursery_sales_kind_valid check (
    sale_kind in ('seedling', 'maquila', 'seed', 'freight', 'other')
  ),
  constraint nursery_sales_terms_valid check (payment_terms in ('cash', 'credit')),
  constraint nursery_sales_total_positive check (total_amount > 0),
  constraint nursery_sales_credit_customer_required check (
    payment_terms <> 'credit' or customer_id is not null
  ),
  constraint nursery_sales_credit_due_date_required check (
    (payment_terms = 'credit' and due_date is not null and due_date >= occurred_at)
    or (payment_terms = 'cash' and due_date is null)
  ),
  constraint nursery_sales_cancellation_complete check (
    (cancelled_at is null and cancellation_reason is null)
    or (cancelled_at is not null and nullif(trim(cancellation_reason), '') is not null)
  )
);

create unique index if not exists nursery_sales_company_source_reference_idx
on public.nursery_sales(company_id, source_reference)
where source_reference is not null;

create index if not exists nursery_sales_nursery_date_idx
on public.nursery_sales(nursery_id, occurred_at desc, id desc);

create index if not exists nursery_sales_customer_due_idx
on public.nursery_sales(company_id, customer_id, due_date)
where cancelled_at is null;

create table if not exists public.nursery_sale_lines (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  sale_id uuid not null,
  catalog_item_id uuid,
  description text not null,
  quantity numeric(14,4),
  unit text,
  unit_price numeric(14,6),
  line_total numeric(14,2) not null,
  created_at timestamptz not null default now(),
  unique (id, company_id),
  foreign key (sale_id, company_id)
    references public.nursery_sales(id, company_id) on delete cascade,
  foreign key (catalog_item_id, company_id)
    references public.nursery_catalog_items(id, company_id) on delete restrict,
  constraint nursery_sale_lines_description_required check (nullif(trim(description), '') is not null),
  constraint nursery_sale_lines_quantity_positive check (quantity is null or quantity > 0),
  constraint nursery_sale_lines_unit_price_non_negative check (unit_price is null or unit_price >= 0),
  constraint nursery_sale_lines_total_positive check (line_total > 0),
  constraint nursery_sale_lines_unit_when_quantity check (
    quantity is null or nullif(trim(unit), '') is not null
  ),
  constraint nursery_sale_lines_arithmetic_check check (
    quantity is null or unit_price is null or round(quantity * unit_price, 2) = line_total
  )
);

create index if not exists nursery_sale_lines_sale_idx
on public.nursery_sale_lines(sale_id);

create table if not exists public.nursery_receipts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  nursery_id uuid not null,
  customer_id uuid,
  receipt_kind text not null default 'sale_payment',
  payment_method text not null,
  occurred_at date not null,
  amount numeric(14,2) not null,
  notes text,
  source_reference text,
  voided_at timestamptz,
  void_reason text,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, company_id),
  foreign key (nursery_id, company_id)
    references public.nurseries(id, company_id) on delete restrict,
  foreign key (customer_id, company_id)
    references public.nursery_customers(id, company_id) on delete restrict,
  constraint nursery_receipts_kind_valid check (
    receipt_kind in ('sale_payment', 'advance', 'settlement', 'other')
  ),
  constraint nursery_receipts_method_valid check (
    payment_method in ('cash', 'transfer', 'other')
  ),
  constraint nursery_receipts_amount_positive check (amount > 0),
  constraint nursery_receipts_advance_customer_required check (
    receipt_kind <> 'advance' or customer_id is not null
  ),
  constraint nursery_receipts_void_complete check (
    (voided_at is null and void_reason is null)
    or (voided_at is not null and nullif(trim(void_reason), '') is not null)
  )
);

create unique index if not exists nursery_receipts_company_source_reference_idx
on public.nursery_receipts(company_id, source_reference)
where source_reference is not null;

create index if not exists nursery_receipts_nursery_date_idx
on public.nursery_receipts(nursery_id, occurred_at desc, id desc);

create table if not exists public.nursery_receipt_allocations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  receipt_id uuid not null,
  sale_id uuid not null,
  amount numeric(14,2) not null,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, company_id),
  unique (receipt_id, sale_id),
  foreign key (receipt_id, company_id)
    references public.nursery_receipts(id, company_id) on delete restrict,
  foreign key (sale_id, company_id)
    references public.nursery_sales(id, company_id) on delete restrict,
  constraint nursery_receipt_allocations_amount_positive check (amount > 0)
);

create index if not exists nursery_receipt_allocations_sale_idx
on public.nursery_receipt_allocations(sale_id);

create table if not exists public.nursery_expenses (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  nursery_id uuid not null,
  occurred_at date not null,
  category text not null,
  amount numeric(14,2) not null,
  quantity numeric(14,4),
  unit text,
  unit_price numeric(14,4),
  payment_method text not null default 'cash',
  supplier text,
  notes text,
  source_reference text,
  voided_at timestamptz,
  void_reason text,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, company_id),
  foreign key (nursery_id, company_id)
    references public.nurseries(id, company_id) on delete restrict,
  constraint nursery_expenses_category_valid check (
    category in (
      'payroll', 'seed', 'tray', 'cover', 'substrate', 'supplies',
      'transport', 'services', 'maintenance', 'freight', 'other'
    )
  ),
  constraint nursery_expenses_amount_positive check (amount > 0),
  constraint nursery_expenses_quantity_positive check (quantity is null or quantity > 0),
  constraint nursery_expenses_unit_price_non_negative check (unit_price is null or unit_price >= 0),
  constraint nursery_expenses_method_valid check (
    payment_method in ('cash', 'transfer', 'other')
  ),
  constraint nursery_expenses_void_complete check (
    (voided_at is null and void_reason is null)
    or (voided_at is not null and nullif(trim(void_reason), '') is not null)
  )
);

create unique index if not exists nursery_expenses_company_source_reference_idx
on public.nursery_expenses(company_id, source_reference)
where source_reference is not null;

create index if not exists nursery_expenses_nursery_date_idx
on public.nursery_expenses(nursery_id, occurred_at desc, id desc);

create table if not exists public.nursery_cash_handoffs (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  nursery_id uuid not null,
  occurred_at date not null,
  amount numeric(14,2) not null,
  receiver_name text not null,
  notes text,
  source_reference text,
  voided_at timestamptz,
  void_reason text,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, company_id),
  foreign key (nursery_id, company_id)
    references public.nurseries(id, company_id) on delete restrict,
  constraint nursery_cash_handoffs_amount_positive check (amount > 0),
  constraint nursery_cash_handoffs_receiver_required check (nullif(trim(receiver_name), '') is not null),
  constraint nursery_cash_handoffs_void_complete check (
    (voided_at is null and void_reason is null)
    or (voided_at is not null and nullif(trim(void_reason), '') is not null)
  )
);

create unique index if not exists nursery_cash_handoffs_company_source_reference_idx
on public.nursery_cash_handoffs(company_id, source_reference)
where source_reference is not null;

create index if not exists nursery_cash_handoffs_nursery_date_idx
on public.nursery_cash_handoffs(nursery_id, occurred_at desc, id desc);

create or replace function public.validate_nursery_receipt_allocation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_receipt public.nursery_receipts%rowtype;
  target_sale public.nursery_sales%rowtype;
  allocated_to_sales numeric;
  allocated_to_sale numeric;
begin
  select * into target_receipt
  from public.nursery_receipts
  where id = new.receipt_id and company_id = new.company_id
  for update;
  if target_receipt.id is null then raise exception 'nursery_receipt_not_found'; end if;
  if target_receipt.voided_at is not null then raise exception 'nursery_receipt_voided'; end if;

  select * into target_sale
  from public.nursery_sales
  where id = new.sale_id and company_id = new.company_id
  for update;
  if target_sale.id is null then raise exception 'nursery_sale_not_found'; end if;
  if target_sale.cancelled_at is not null then raise exception 'nursery_sale_cancelled'; end if;
  if target_receipt.nursery_id <> target_sale.nursery_id then raise exception 'nursery_allocation_scope_mismatch'; end if;
  if target_receipt.customer_id is not null and target_sale.customer_id is not null
    and target_receipt.customer_id <> target_sale.customer_id
    then raise exception 'nursery_allocation_customer_mismatch';
  end if;

  select coalesce(sum(allocation.amount), 0) into allocated_to_sales
  from public.nursery_receipt_allocations allocation
  where allocation.receipt_id = new.receipt_id
    and allocation.id <> new.id;
  if allocated_to_sales + new.amount > target_receipt.amount then
    raise exception 'nursery_receipt_overallocated';
  end if;

  select coalesce(sum(allocation.amount), 0) into allocated_to_sale
  from public.nursery_receipt_allocations allocation
  join public.nursery_receipts receipt on receipt.id = allocation.receipt_id
  where allocation.sale_id = new.sale_id
    and allocation.id <> new.id
    and receipt.voided_at is null;
  if allocated_to_sale + new.amount > target_sale.total_amount then
    raise exception 'nursery_sale_overpayment';
  end if;

  return new;
end;
$$;

drop trigger if exists validate_nursery_receipt_allocation on public.nursery_receipt_allocations;
create trigger validate_nursery_receipt_allocation
before insert or update on public.nursery_receipt_allocations
for each row execute function public.validate_nursery_receipt_allocation();

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'nurseries', 'nursery_customers', 'nursery_catalog_items', 'nursery_sales',
    'nursery_receipts', 'nursery_receipt_allocations', 'nursery_expenses',
    'nursery_cash_handoffs'
  ]
  loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I', target_table, target_table);
    execute format(
      'create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      target_table,
      target_table
    );
  end loop;
end $$;

create or replace view public.nursery_sale_balances
with (security_invoker = true)
as
select
  sale.id,
  sale.folio,
  sale.company_id,
  sale.nursery_id,
  sale.customer_id,
  sale.sale_kind,
  sale.payment_terms,
  sale.occurred_at,
  sale.due_date,
  sale.total_amount,
  coalesce(sum(allocation.amount) filter (where receipt.voided_at is null), 0)::numeric(14,2) as paid_amount,
  greatest(
    sale.total_amount - coalesce(sum(allocation.amount) filter (where receipt.voided_at is null), 0),
    0
  )::numeric(14,2) as balance_amount,
  case
    when sale.cancelled_at is not null then 'cancelled'
    when sale.total_amount - coalesce(sum(allocation.amount) filter (where receipt.voided_at is null), 0) <= 0 then 'paid'
    when sale.due_date is not null and sale.due_date < current_date then 'overdue'
    when coalesce(sum(allocation.amount) filter (where receipt.voided_at is null), 0) > 0 then 'partial'
    else 'pending'
  end as payment_status,
  sale.notes,
  sale.source_reference,
  sale.cancelled_at,
  sale.created_at,
  sale.updated_at
from public.nursery_sales sale
left join public.nursery_receipt_allocations allocation on allocation.sale_id = sale.id
left join public.nursery_receipts receipt on receipt.id = allocation.receipt_id
group by sale.id;

create or replace view public.nursery_cash_ledger
with (security_invoker = true)
as
select receipt.company_id, receipt.nursery_id, receipt.occurred_at,
  'receipt'::text as movement_type, receipt.payment_method,
  receipt.amount::numeric(14,2) as signed_amount, receipt.id as source_id,
  coalesce(nullif(trim(receipt.notes), ''), receipt.receipt_kind) as description
from public.nursery_receipts receipt
where receipt.voided_at is null
union all
select expense.company_id, expense.nursery_id, expense.occurred_at,
  'expense'::text, expense.payment_method,
  (-expense.amount)::numeric(14,2), expense.id,
  coalesce(nullif(trim(expense.notes), ''), expense.category)
from public.nursery_expenses expense
where expense.voided_at is null
union all
select handoff.company_id, handoff.nursery_id, handoff.occurred_at,
  'cash_handoff'::text, 'cash'::text,
  (-handoff.amount)::numeric(14,2), handoff.id,
  'Entrega a ' || handoff.receiver_name
from public.nursery_cash_handoffs handoff
where handoff.voided_at is null;

create or replace function public.create_nursery_sale(
  target_nursery_id uuid,
  target_customer_id uuid,
  target_occurred_at date,
  target_sale_kind text,
  target_payment_terms text,
  target_due_date date,
  target_notes text,
  target_lines jsonb,
  target_initial_receipt_amount numeric,
  target_payment_method text,
  target_source_reference text,
  target_receipt_source_reference text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_nursery public.nurseries%rowtype;
  target_sale public.nursery_sales%rowtype;
  target_receipt public.nursery_receipts%rowtype;
  target_company_id uuid;
  line jsonb;
  line_catalog_item_id uuid;
  line_description text;
  line_quantity numeric;
  line_unit text;
  line_unit_price numeric;
  line_total numeric;
  sale_total numeric := 0;
  existing_balance public.nursery_sale_balances%rowtype;
begin
  select * into target_nursery from public.nurseries
  where id = target_nursery_id and is_active = true;
  if target_nursery.id is null then raise exception 'nursery_not_found'; end if;
  target_company_id := target_nursery.company_id;
  if not public.can_manage_company(target_company_id) then raise exception 'not_allowed'; end if;

  if nullif(trim(target_source_reference), '') is not null then
    select balance.* into existing_balance
    from public.nursery_sale_balances balance
    where balance.company_id = target_company_id
      and balance.source_reference = nullif(trim(target_source_reference), '');
    if existing_balance.id is not null then
      if existing_balance.nursery_id <> target_nursery_id then
        raise exception 'nursery_sale_source_reference_conflict';
      end if;
      return jsonb_build_object(
        'saleId', existing_balance.id,
        'totalAmount', existing_balance.total_amount,
        'paidAmount', existing_balance.paid_amount,
        'balanceAmount', existing_balance.balance_amount,
        'paymentStatus', existing_balance.payment_status,
        'idempotent', true
      );
    end if;
  end if;

  if target_customer_id is not null and not exists (
    select 1 from public.nursery_customers customer
    where customer.id = target_customer_id
      and customer.company_id = target_company_id
      and customer.is_active = true
  ) then raise exception 'nursery_customer_not_found'; end if;
  if target_payment_terms not in ('cash', 'credit') then raise exception 'nursery_sale_terms_invalid'; end if;
  if target_sale_kind not in ('seedling', 'maquila', 'seed', 'freight', 'other') then raise exception 'nursery_sale_kind_invalid'; end if;
  if target_occurred_at is null then raise exception 'nursery_sale_date_required'; end if;
  if target_payment_terms = 'credit' and target_customer_id is null then raise exception 'nursery_credit_customer_required'; end if;
  if target_payment_terms = 'credit' and (target_due_date is null or target_due_date < target_occurred_at)
    then raise exception 'nursery_credit_due_date_invalid';
  end if;
  if target_payment_terms = 'cash' and target_due_date is not null then raise exception 'nursery_cash_due_date_not_allowed'; end if;
  if jsonb_typeof(coalesce(target_lines, '[]'::jsonb)) <> 'array'
    or jsonb_array_length(coalesce(target_lines, '[]'::jsonb)) = 0
    then raise exception 'nursery_sale_lines_required';
  end if;

  for line in select value from jsonb_array_elements(target_lines)
  loop
    line_description := nullif(trim(line->>'description'), '');
    line_catalog_item_id := nullif(line->>'catalogItemId', '')::uuid;
    line_quantity := nullif(line->>'quantity', '')::numeric;
    line_unit := nullif(trim(line->>'unit'), '');
    line_unit_price := nullif(line->>'unitPrice', '')::numeric;
    line_total := nullif(line->>'lineTotal', '')::numeric;
    if line_description is null then raise exception 'nursery_sale_line_description_required'; end if;
    if line_catalog_item_id is not null and not exists (
      select 1 from public.nursery_catalog_items item
      where item.id = line_catalog_item_id
        and item.company_id = target_company_id
        and item.nursery_id = target_nursery_id
        and item.is_active = true
    ) then raise exception 'nursery_catalog_item_not_found'; end if;
    if line_quantity is not null and line_quantity <= 0 then raise exception 'nursery_sale_line_quantity_invalid'; end if;
    if line_quantity is not null and line_unit is null then raise exception 'nursery_sale_line_unit_required'; end if;
    if line_unit_price is not null and line_unit_price < 0 then raise exception 'nursery_sale_line_unit_price_invalid'; end if;
    if line_total is null or line_total <= 0 then raise exception 'nursery_sale_line_total_invalid'; end if;
    if line_quantity is not null and line_unit_price is not null
      and round(line_quantity * line_unit_price, 2) <> round(line_total, 2)
      then raise exception 'nursery_sale_line_amount_mismatch';
    end if;
    sale_total := sale_total + round(line_total, 2);
  end loop;

  target_initial_receipt_amount := coalesce(target_initial_receipt_amount, 0);
  if target_initial_receipt_amount < 0 then raise exception 'nursery_receipt_amount_invalid'; end if;
  if target_payment_terms = 'cash' and round(target_initial_receipt_amount, 2) <> round(sale_total, 2)
    then raise exception 'nursery_cash_sale_must_be_paid';
  end if;
  if target_payment_terms = 'credit' and target_initial_receipt_amount > sale_total
    then raise exception 'nursery_sale_overpayment';
  end if;
  if target_initial_receipt_amount > 0 and target_payment_method not in ('cash', 'transfer', 'other')
    then raise exception 'nursery_payment_method_invalid';
  end if;

  insert into public.nursery_sales (
    company_id, nursery_id, customer_id, sale_kind, payment_terms,
    occurred_at, due_date, total_amount, notes, source_reference, created_by
  ) values (
    target_company_id, target_nursery_id, target_customer_id, target_sale_kind, target_payment_terms,
    target_occurred_at, target_due_date, round(sale_total, 2), nullif(trim(target_notes), ''),
    nullif(trim(target_source_reference), ''), auth.uid()
  ) returning * into target_sale;

  for line in select value from jsonb_array_elements(target_lines)
  loop
    line_description := nullif(trim(line->>'description'), '');
    line_catalog_item_id := nullif(line->>'catalogItemId', '')::uuid;
    line_quantity := nullif(line->>'quantity', '')::numeric;
    line_unit := nullif(trim(line->>'unit'), '');
    line_unit_price := nullif(line->>'unitPrice', '')::numeric;
    line_total := nullif(line->>'lineTotal', '')::numeric;
    insert into public.nursery_sale_lines (
      company_id, sale_id, catalog_item_id, description, quantity, unit, unit_price, line_total
    ) values (
      target_company_id, target_sale.id, line_catalog_item_id,
      line_description, line_quantity, line_unit, line_unit_price, round(line_total, 2)
    );
  end loop;

  if target_initial_receipt_amount > 0 then
    insert into public.nursery_receipts (
      company_id, nursery_id, customer_id, receipt_kind, payment_method,
      occurred_at, amount, notes, source_reference, created_by
    ) values (
      target_company_id, target_nursery_id, target_customer_id, 'sale_payment', target_payment_method,
      target_occurred_at, round(target_initial_receipt_amount, 2), 'Cobro inicial de venta',
      nullif(trim(target_receipt_source_reference), ''), auth.uid()
    ) returning * into target_receipt;
    insert into public.nursery_receipt_allocations (
      company_id, receipt_id, sale_id, amount, created_by
    ) values (
      target_company_id, target_receipt.id, target_sale.id, round(target_initial_receipt_amount, 2), auth.uid()
    );
  end if;

  return jsonb_build_object(
    'saleId', target_sale.id,
    'receiptId', target_receipt.id,
    'totalAmount', round(sale_total, 2),
    'paidAmount', round(target_initial_receipt_amount, 2),
    'balanceAmount', round(sale_total - target_initial_receipt_amount, 2),
    'paymentStatus', case
      when target_initial_receipt_amount >= sale_total then 'paid'
      when target_initial_receipt_amount > 0 then 'partial'
      else 'pending'
    end,
    'idempotent', false
  );
end;
$$;

create or replace function public.record_nursery_payment(
  target_sale_id uuid,
  target_occurred_at date,
  target_amount numeric,
  target_payment_method text,
  target_receipt_kind text,
  target_notes text,
  target_source_reference text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_sale public.nursery_sales%rowtype;
  target_receipt public.nursery_receipts%rowtype;
  existing_receipt public.nursery_receipts%rowtype;
  current_paid numeric;
begin
  select * into target_sale from public.nursery_sales
  where id = target_sale_id for update;
  if target_sale.id is null then raise exception 'nursery_sale_not_found'; end if;
  if not public.can_manage_company(target_sale.company_id) then raise exception 'not_allowed'; end if;
  if target_sale.cancelled_at is not null then raise exception 'nursery_sale_cancelled'; end if;

  if nullif(trim(target_source_reference), '') is not null then
    select * into existing_receipt from public.nursery_receipts
    where company_id = target_sale.company_id
      and source_reference = nullif(trim(target_source_reference), '');
    if existing_receipt.id is not null then
      if not exists (
        select 1 from public.nursery_receipt_allocations allocation
        where allocation.receipt_id = existing_receipt.id and allocation.sale_id = target_sale.id
      ) then raise exception 'nursery_receipt_source_reference_conflict'; end if;
      select coalesce(sum(allocation.amount), 0) into current_paid
      from public.nursery_receipt_allocations allocation
      join public.nursery_receipts receipt on receipt.id = allocation.receipt_id
      where allocation.sale_id = target_sale.id and receipt.voided_at is null;
      return jsonb_build_object(
        'receiptId', existing_receipt.id,
        'saleId', target_sale.id,
        'paidAmount', current_paid,
        'balanceAmount', greatest(target_sale.total_amount - current_paid, 0),
        'idempotent', true
      );
    end if;
  end if;

  if target_occurred_at is null then raise exception 'nursery_receipt_date_required'; end if;
  if target_amount is null or target_amount <= 0 then raise exception 'nursery_receipt_amount_invalid'; end if;
  if target_payment_method not in ('cash', 'transfer', 'other') then raise exception 'nursery_payment_method_invalid'; end if;
  if target_receipt_kind not in ('sale_payment', 'settlement') then raise exception 'nursery_payment_kind_invalid'; end if;

  select coalesce(sum(allocation.amount), 0) into current_paid
  from public.nursery_receipt_allocations allocation
  join public.nursery_receipts receipt on receipt.id = allocation.receipt_id
  where allocation.sale_id = target_sale.id and receipt.voided_at is null;
  if current_paid + target_amount > target_sale.total_amount then raise exception 'nursery_sale_overpayment'; end if;

  insert into public.nursery_receipts (
    company_id, nursery_id, customer_id, receipt_kind, payment_method,
    occurred_at, amount, notes, source_reference, created_by
  ) values (
    target_sale.company_id, target_sale.nursery_id, target_sale.customer_id,
    target_receipt_kind, target_payment_method, target_occurred_at, round(target_amount, 2),
    nullif(trim(target_notes), ''), nullif(trim(target_source_reference), ''), auth.uid()
  ) returning * into target_receipt;

  insert into public.nursery_receipt_allocations (
    company_id, receipt_id, sale_id, amount, created_by
  ) values (
    target_sale.company_id, target_receipt.id, target_sale.id, round(target_amount, 2), auth.uid()
  );

  current_paid := current_paid + round(target_amount, 2);
  return jsonb_build_object(
    'receiptId', target_receipt.id,
    'saleId', target_sale.id,
    'paidAmount', current_paid,
    'balanceAmount', greatest(target_sale.total_amount - current_paid, 0),
    'idempotent', false
  );
end;
$$;

create or replace function public.record_nursery_receipt(
  target_nursery_id uuid,
  target_customer_id uuid,
  target_occurred_at date,
  target_amount numeric,
  target_payment_method text,
  target_receipt_kind text,
  target_notes text,
  target_source_reference text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_nursery public.nurseries%rowtype;
  target_receipt public.nursery_receipts%rowtype;
begin
  select * into target_nursery from public.nurseries
  where id = target_nursery_id and is_active = true;
  if target_nursery.id is null then raise exception 'nursery_not_found'; end if;
  if not public.can_manage_company(target_nursery.company_id) then raise exception 'not_allowed'; end if;
  if target_receipt_kind not in ('advance', 'other') then raise exception 'nursery_unallocated_receipt_kind_invalid'; end if;
  if target_receipt_kind = 'advance' and target_customer_id is null then raise exception 'nursery_advance_customer_required'; end if;
  if target_customer_id is not null and not exists (
    select 1 from public.nursery_customers customer
    where customer.id = target_customer_id
      and customer.company_id = target_nursery.company_id
      and customer.is_active = true
  ) then raise exception 'nursery_customer_not_found'; end if;
  if target_occurred_at is null then raise exception 'nursery_receipt_date_required'; end if;
  if target_amount is null or target_amount <= 0 then raise exception 'nursery_receipt_amount_invalid'; end if;
  if target_payment_method not in ('cash', 'transfer', 'other') then raise exception 'nursery_payment_method_invalid'; end if;

  if nullif(trim(target_source_reference), '') is not null then
    select * into target_receipt from public.nursery_receipts
    where company_id = target_nursery.company_id
      and source_reference = nullif(trim(target_source_reference), '');
    if target_receipt.id is not null then
      if target_receipt.nursery_id <> target_nursery_id then raise exception 'nursery_receipt_source_reference_conflict'; end if;
      return jsonb_build_object('receiptId', target_receipt.id, 'idempotent', true);
    end if;
  end if;

  insert into public.nursery_receipts (
    company_id, nursery_id, customer_id, receipt_kind, payment_method,
    occurred_at, amount, notes, source_reference, created_by
  ) values (
    target_nursery.company_id, target_nursery_id, target_customer_id,
    target_receipt_kind, target_payment_method, target_occurred_at,
    round(target_amount, 2), nullif(trim(target_notes), ''),
    nullif(trim(target_source_reference), ''), auth.uid()
  ) returning * into target_receipt;
  return jsonb_build_object('receiptId', target_receipt.id, 'idempotent', false);
end;
$$;

create or replace function public.allocate_nursery_receipt(
  target_receipt_id uuid,
  target_sale_id uuid,
  target_amount numeric
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_receipt public.nursery_receipts%rowtype;
  target_allocation public.nursery_receipt_allocations%rowtype;
begin
  select * into target_receipt from public.nursery_receipts
  where id = target_receipt_id for update;
  if target_receipt.id is null then raise exception 'nursery_receipt_not_found'; end if;
  if not public.can_manage_company(target_receipt.company_id) then raise exception 'not_allowed'; end if;
  if target_receipt.voided_at is not null then raise exception 'nursery_receipt_voided'; end if;
  if target_amount is null or target_amount <= 0 then raise exception 'nursery_allocation_amount_invalid'; end if;

  insert into public.nursery_receipt_allocations (
    company_id, receipt_id, sale_id, amount, created_by
  ) values (
    target_receipt.company_id, target_receipt.id, target_sale_id, round(target_amount, 2), auth.uid()
  )
  on conflict (receipt_id, sale_id) do update
  set amount = public.nursery_receipt_allocations.amount + excluded.amount,
      updated_at = now()
  returning * into target_allocation;

  return jsonb_build_object(
    'allocationId', target_allocation.id,
    'receiptId', target_allocation.receipt_id,
    'saleId', target_allocation.sale_id,
    'allocatedAmount', target_allocation.amount
  );
end;
$$;

create or replace function public.void_nursery_receipt(
  target_receipt_id uuid,
  target_reason text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_receipt public.nursery_receipts%rowtype;
begin
  select * into target_receipt from public.nursery_receipts
  where id = target_receipt_id for update;
  if target_receipt.id is null then raise exception 'nursery_receipt_not_found'; end if;
  if not public.can_manage_company(target_receipt.company_id) then raise exception 'not_allowed'; end if;
  if nullif(trim(target_reason), '') is null then raise exception 'nursery_void_reason_required'; end if;
  if target_receipt.voided_at is null then
    update public.nursery_receipts
    set voided_at = now(), void_reason = trim(target_reason), updated_at = now()
    where id = target_receipt.id returning * into target_receipt;
  end if;
  return jsonb_build_object('receiptId', target_receipt.id, 'voidedAt', target_receipt.voided_at);
end;
$$;

create or replace function public.cancel_nursery_sale(
  target_sale_id uuid,
  target_reason text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_sale public.nursery_sales%rowtype;
  active_paid numeric;
begin
  select * into target_sale from public.nursery_sales
  where id = target_sale_id for update;
  if target_sale.id is null then raise exception 'nursery_sale_not_found'; end if;
  if not public.can_manage_company(target_sale.company_id) then raise exception 'not_allowed'; end if;
  if nullif(trim(target_reason), '') is null then raise exception 'nursery_cancellation_reason_required'; end if;
  select coalesce(sum(allocation.amount), 0) into active_paid
  from public.nursery_receipt_allocations allocation
  join public.nursery_receipts receipt on receipt.id = allocation.receipt_id
  where allocation.sale_id = target_sale.id and receipt.voided_at is null;
  if active_paid > 0 then raise exception 'nursery_sale_has_active_receipts'; end if;
  if target_sale.cancelled_at is null then
    update public.nursery_sales
    set cancelled_at = now(), cancellation_reason = trim(target_reason), updated_at = now()
    where id = target_sale.id returning * into target_sale;
  end if;
  return jsonb_build_object('saleId', target_sale.id, 'cancelledAt', target_sale.cancelled_at);
end;
$$;

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'nurseries', 'nursery_customers', 'nursery_catalog_items', 'nursery_sales',
    'nursery_sale_lines', 'nursery_receipts', 'nursery_receipt_allocations',
    'nursery_expenses', 'nursery_cash_handoffs'
  ]
  loop
    execute format('alter table public.%I enable row level security', target_table);
    execute format('drop policy if exists %I on public.%I', target_table || '_select_owner_admin', target_table);
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.can_manage_company(company_id))',
      target_table || '_select_owner_admin',
      target_table
    );
  end loop;
end $$;

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'nurseries', 'nursery_customers', 'nursery_catalog_items',
    'nursery_expenses', 'nursery_cash_handoffs'
  ]
  loop
    execute format('drop policy if exists %I on public.%I', target_table || '_insert_owner_admin', target_table);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (public.can_manage_company(company_id))',
      target_table || '_insert_owner_admin',
      target_table
    );
    execute format('drop policy if exists %I on public.%I', target_table || '_update_owner_admin', target_table);
    execute format(
      'create policy %I on public.%I for update to authenticated using (public.can_manage_company(company_id)) with check (public.can_manage_company(company_id))',
      target_table || '_update_owner_admin',
      target_table
    );
  end loop;
end $$;

revoke all on table public.nurseries from public, anon, authenticated;
revoke all on table public.nursery_customers from public, anon, authenticated;
revoke all on table public.nursery_catalog_items from public, anon, authenticated;
revoke all on table public.nursery_sales from public, anon, authenticated;
revoke all on table public.nursery_sale_lines from public, anon, authenticated;
revoke all on table public.nursery_receipts from public, anon, authenticated;
revoke all on table public.nursery_receipt_allocations from public, anon, authenticated;
revoke all on table public.nursery_expenses from public, anon, authenticated;
revoke all on table public.nursery_cash_handoffs from public, anon, authenticated;

grant select, insert, update on table public.nurseries to authenticated;
grant select, insert, update on table public.nursery_customers to authenticated;
grant select, insert, update on table public.nursery_catalog_items to authenticated;
grant select on table public.nursery_sales to authenticated;
grant select on table public.nursery_sale_lines to authenticated;
grant select on table public.nursery_receipts to authenticated;
grant select on table public.nursery_receipt_allocations to authenticated;
grant select, insert, update on table public.nursery_expenses to authenticated;
grant select, insert, update on table public.nursery_cash_handoffs to authenticated;
grant usage, select on sequence public.nursery_sales_folio_seq to authenticated;

revoke all on table public.nursery_sale_balances from public, anon;
revoke all on table public.nursery_cash_ledger from public, anon;
grant select on table public.nursery_sale_balances to authenticated;
grant select on table public.nursery_cash_ledger to authenticated;

revoke all on function public.validate_nursery_receipt_allocation() from public, anon, authenticated;

revoke all on function public.create_nursery_sale(uuid, uuid, date, text, text, date, text, jsonb, numeric, text, text, text) from public, anon;
grant execute on function public.create_nursery_sale(uuid, uuid, date, text, text, date, text, jsonb, numeric, text, text, text) to authenticated;

revoke all on function public.record_nursery_payment(uuid, date, numeric, text, text, text, text) from public, anon;
grant execute on function public.record_nursery_payment(uuid, date, numeric, text, text, text, text) to authenticated;

revoke all on function public.record_nursery_receipt(uuid, uuid, date, numeric, text, text, text, text) from public, anon;
grant execute on function public.record_nursery_receipt(uuid, uuid, date, numeric, text, text, text, text) to authenticated;

revoke all on function public.allocate_nursery_receipt(uuid, uuid, numeric) from public, anon;
grant execute on function public.allocate_nursery_receipt(uuid, uuid, numeric) to authenticated;

revoke all on function public.void_nursery_receipt(uuid, text) from public, anon;
grant execute on function public.void_nursery_receipt(uuid, text) to authenticated;

revoke all on function public.cancel_nursery_sale(uuid, text) from public, anon;
grant execute on function public.cancel_nursery_sale(uuid, text) to authenticated;
